### ISSUE TITLE
Apos is not defined in index of apostrophe-favicon-global

### ISSUE THREAD

**Issue by kalidis** [apostrophecms/apostrophe-favicons#17]
Trying v2.0.0 on existing project and in new proyect gives me the same error:

`/home/kalia/Escritorio/test-faviocns/node_modules/apostrophe-favicons/lib/modules/apostrophe-favicons-global/index.js:143`
`apos.utils.error(err);`

`ReferenceError: apos is not defined`

But debugging, the real error that been throw was

`Error: ENOENT: no such file or directory, access '/home/kalia/Escritorio/test-favicons/data/temp/uploadfs/tempAposFavicons'`

[Test project](https://github.com/kalidis/test-favicons )

**Comment by boutell** [comment]
Fixed in 2.0.2.
